;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dap-tooltip-mouse-motion
	hungry-delete-backward
	hydra-move/backward-char
	hydra-move/forward-char
	kill-region
	org-self-insert-command
	rjsx-delete-creates-full-tag
	wdired--self-insert
	wdired-finish-edit
	yaml-electric-backspace
	yaml-electric-dash-and-dot
	))

(setq mc/cmds-to-run-once
      '(
	helm-M-x
	helm-confirm-and-exit-minibuffer
	hydra-multi-cursors/mc-mark-next-like-this-then-cycle-forward
	hydra-multi-cursors/mc-mark-previous-like-this-then-cycle-backward
	hydra-multi-cursors/mc-skip-to-next-like-this-then-cycle-forward
	hydra-multi-cursors/mc-skip-to-previous-like-this-then-cycle-backward
	hydra-multi-cursors/mc/mark-all-like-this
	hydra-multi-cursors/mc/unmark-next-like-this
	hydra-multi-cursors/mc/unmark-previous-like-this
	))
