;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	))

(setq mc/cmds-to-run-once
      '(
	cqql-multiple-cursors-hydra/mc/mark-all-like-this-and-exit
	cqql-multiple-cursors-hydra/mc/mark-next-like-this
	cqql-multiple-cursors-hydra/mc/mark-next-like-this-and-exit
	cqql-multiple-cursors-hydra/mc/mark-previous-like-this
	cqql-multiple-cursors-hydra/mc/skip-to-next-like-this
	helm-M-x
	helm-confirm-and-exit-minibuffer
	hydra-multi-cursors/mc/mark-all-like-this-and-exit
	hydra-multi-cursors/mc/mark-next-like-this
	hydra-multi-cursors/mc/mark-previous-like-this
	hydra-multi-cursors/mc/skip-to-next-like-this
	))
