;; MELPA package
(require 'package)
;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'benchmark-init)
(add-hook 'ater-init-hook 'benchmark-init/deactivate)

(require 'init-basic-env)
(require 'init-swiper)
(require 'init-smartparens)
(require 'init-helm)
(require 'init-company)
(require 'init-anaconda)
(require 'init-flycheck)
(require 'init-magit)
(require 'init-clang)
(require 'init-tide)
(require 'init-omnisharp)
(require 'init-web)
(require 'init-avy)
(require 'init-hydra)
(require 'init-ace-window)
(require 'init-projectile)
(require 'init-yasnippet)
(require 'init-neotree)

(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)
